server:
    port: 8081

#spring
spring:
  resources:
    static-locations: file:${oss.local.upload-file-path}
  session:
     store-type: none
  devtools:
    restart:
      enabled: true        #这里是为了热部署的，与mybatis是无关的
  cache:
    type: GENERIC    #redis这里是缓存设置
  mail:                    #邮件发送
    host: smtp.exmail.qq.com
    username: jeeweb@jeeweb.cn
    sender: jeeweb@jeeweb.cn
    password: 您的密码
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
             port: 465
             class: javax.net.ssl.SSLSocketFactory
             fallback: false
  redis:   #redis 配置
        host: localhost
        port: 6379
        password:
        jedis:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: 10000
  messages: #国际化
      basename: i18n/messages,i18n/ValidationMessages
  mvc: # 捕获404
    throw-exception-if-no-handler-found: true
  resources:
   add-mappings: false
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  aop:  #使用CGLIB来实现AOP的时候
     proxy-target-class: true
     auto: true

  #DATABASE CONFIG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 您的密码
    url: jdbc:mysql://localhost:3306/jeeweb_bbs?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.jeeweb.bbs.modules.*.entity  #这里是实体类的位置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  cn.jeeweb.bbs.modules.*.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型

#logging
#logging:
  #level: warn

#shiro
shiro:
   loginUrl: /user/login
   rememeberMeCookieName: jeeweb-bbs-rememeberMeCache
   rememeberMeCookieBase64CipherKey: l8cc6d2xpkT1yFtLIcLHCg== #生成方式KeyGenerator keygen = KeyGenerator.getInstance("AES");SecretKey deskey = keygen.generateKey();System.out.println(Base64.encodeToString(deskey.getEncoded()));
   filter-chain-definitions: /example/create=user;/user/home/*=anon;/example/**=anon;/posts/add=user;/posts/*/update=user;/posts/comment/**=user;/posts/*/delete=user;/posts/**=anon;/auth/**=anon;/=anon;/user/forget=anon;/user/login=anon;/user/reset=anon;/user/activate=anon;/user/*/vercode=anon;/user/register=anon;/user/logout=anon;/static/**=anon;/jcaptcha*=anon;/upload/**=anon;/admin/logout=logout;/admin/login=jCaptchaValidate,authc;/**=user,sysUser,onlineSession,perms,roles

#后台路径配置
jeeweb:
  staticPath: /static
  admin:
     url:
       prefix: /admin
       suffix: .html
     default:
       theme: uadmin

#beetl配置
beetlsql:
  enabled: false
beetl:
  enabled: false
  suffix: html
  templatesPath: views
  importPackage: cn.jeeweb.common.utils.;

#文件上传配置
#使用的上传存储空间,local本地,aliyun:阿里云
oss:
 client-type: aliyun
 #默认上传目录
 base_dir:
 #允许的文件扩展名
 allowed_extension: mp4,bmp, gif, jpg, jpeg, png,doc, docx, xls, xlsx, ppt, pptx,html,htm,txt,rar, zip, gz, bz2,pdf
 #最大文件大小 50M
 max_size: 52428800
 local:
   domain: http://localhost:8080
   upload-file-path: D:/hhaha
 aliyun:
   #阿里云api的内或外网域名
   endpoint: oss-cn-beijing.aliyuncs.com
   #阿里云api的密钥access key id
   access-key-id: 阿里云ID
   #阿里云api的密钥access key secret
   access-key-secret: 阿里云 key
   #阿里云api的bucket名称
   bucket-name: jeewebbbs
   #外部访问域名
   domain: https://jeewebbbs.oss-cn-beijing.aliyuncs.com

#短信配置
sms:
 client-type: aliyun
 open: true
 sign-name: 立行教育
 aliyun:
   #阿里云api的密钥access key id
   access-key-id: 阿里云ID
   #阿里云api的密钥access key secret
   access-key-secret: 阿里云 key

#定时任务配置
quartz:
  open-cluster: false # 是否开启集群
  config-location: /quartz/quartz.properties # 集群配置文件路径
  data-source: qzDS # 集群数据库，使用当前数据库可以设置为空或者default

#支付配置
pay:
  alipay:
     app-id: 2016092200567766
     pid: 2088102176719631
     key-public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu6wl0PLTkouXNWp+Uy5HRtUo0U3TKaWuuKlrTXfN+ThPOzPZ0LFhBkp29HJCSTJI6UnqWfKHcCdtTD4iWBPG4TMKqYOfPPgqvhwmEwXxarqK1/jKMTrHYdWvhUOU+2cMlw+tIxmxQjPulcV5hG21UUH0Vkyv5ey4Pi8lZqpxItb2WSX0jpL2RRMDTqgaBNZbqhASxznGy/IlvzOeSWTFd+e3XfiogxoKz1cIOvXFB0Kz9ebO+fAOC7XrxJItAgeJonWIq34eiGQ4SX1mirq7z6yzJPR4h5vh0D7rtLl5nRMlJv8XTSrz57FPplyzxKCffGzMxYwnE+z7sJUabIs9KQIDAQAB
     key-private: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCOitvuoNupE30LFG/ZGEkxJdpf23EmqekVYUlGozfNMwrcv+4FyXWCmS2/kqCx30LtmHcaUOSW/E4k1kv/9nmF1ju539airaxtVw1OwRpvgIRjMST1wmfiAXY5+mYGsANgbdITCoiRfqEht9iOPR8xlp2/zwQURTBYKUnc1DQU7Q5hE/scyq1/smLuST/YkE4cv/aIZOVEdJXCaXKf/94UB9vdQOW+3TH/akOuDGMiDXRuyTOsUVW4bmcnGu6P/yVn95E3XA7UKkFfzcsa90LSlvrywwUZ4LEafvFkoqzxSUHNyTNV6nTR/sKbkXZ/MviEFGHdmdAlyi3Dsrenmb03AgMBAAECggEAC68eMAVHfCh4y3u1X1o6RakQqWLXd4/d5z6+PugKHuvcLBQfcqH82+OqeFWQjoP6fHdO6/1Nf4LW9PYL7MNLWskgxC+w7EzIIX5NPPNfM1yZfXf9y5dP5JqyEjaQPmQXIsRdv+nRH/v9QUJMofwonmv2Kk7RyseRGujngQ5z5nMYqvea8r61M9BCOdA3qXKLCqG5vQwP7dEwS2kUaL2hVusFIhK4N5rfo7whUTqpqDDg/gbB2WefNLcD36UaQrGK1pwt76Z+DkRKoja0Wuasrlyz8xpciB7KlDrf2xjCMu+/tsS0Dz0zH7Zw1SPCPxarHtRRYitibmcvPWB4LLQuAQKBgQDJFe3nJWABj1mG7LA3Ohwlg5SmkhJ6sGO8r/L3kI/WoOvko/8f4PgGo+O6vLsIfpv2qp0kejh2qHDVSbDsqle0BmRI+Tyl/9ZZS6OwjY2qvGv8Uyri0rl3kPeTh4lHHmAEkLcrfChYXws0cIYWjIcg1ZiZjvoI0Gnb+WBM0fxqwQKBgQC1eB8f3QhQtArMqHZ2JR2YPpbNo1E54ZgWCpT8+ZwnQbjXh2rWVvsgXjSE3/j12yxuYN8/CHjp6WE8JpCcsEpZKlfIiWV5whtw0rf94hfWwCIdtBIllz67ldmE2K+LAkg7NmEAnCDtId06ICaplNf16yB3XdZESzJNYR1aAQ799wKBgQCqotY/yIKAsGFbUmxyYPhTiSXSd7AAtr/b9T7rf5vfmKy0V8n+BkzSba6o3tCj87Rri/pPYvuZDXS6OY9ONXq5BJeDKSSjBMei/MHJ50TpNn04IGcLFaBW6wh8A46lcAwws5EL8I7X9scuV7IhXlyoqziUTjS02A6MoUBrz+EvwQKBgBi5Wfw8YCKmtQX3OdSU7/hLJr6zrqBlNRRjsrLYy0ap9KYgxBSZ2zMowp0L6t6MUvxi5GexHtA3xNCuLGu8tRR66WTgG1xAbv6rJvhHMppGqR9E5mgKuDhUjUNFRn14/SBcI1Ey9GV6hKqjsMDQD7BorY610TiSyjKytY4KsOE3AoGAFI6ek0CXJ55vId9uCsnv7ANkKvg7476porB/FIXmJsTqiD55saajjOnxVq3jz1MaR74zWI9mULGhpGU3MXcJnWFYWdjWVUbtEfoRaUNMIJezn044A1ys2zEM0FSN1eOEiZefUJYhuaj963bEBLu3GeNFhJDN/lbqoiyzrspVguk=
     notify-url: http://yanyuanboyi.gicp.net:28321/product/payBack
     return-url: http://yanyuanboyi.gicp.net:28321/product/payBack
     sign-type: RSA2
     seller: 2088102176719631
     input-charset: utf-8
     test: true

#swagger配置
swagger:
  enabled: true
  title: Jeebbs管理系统_接口文档
  description: 描述：具体包括XXX,XXX模块...
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://gitee.com/dataact/jeebbs
  contact.name: 王存见
  contact.url: http://www.jeeweb.cn
  contact.email: 502079461@qq.com
  base-package: cn.jeeweb.bbs
  base-path: /**
  exclude-path: /error, /ops/**